var bullets = [
  'A bad beginning makes a bad ending. <br>不善始者不善终。',
  'A bad thing never dies. <br>遗臭万年。',
  'A bad workman always blames his tools. <br>不会撑船怪河弯。',
  'A bird in the hand is worth than two in the bush. <br>一鸟在手胜过双鸟在林。',
  'A boaster and a liar are cousins-german. <br>吹牛与说谎本是同宗。',
  'A bully is always a coward. <br>色厉内荏。',
  'A burden of one\'s choice is not felt. <br>爱挑的担子不嫌重。',
  'A candle lights others and consumes itself. <br>蜡烛照亮别人，却毁灭了自己。',
  'A cat has 9 lives. <br>猫有九条命。',
  'A cat may look at a king. <br>人人平等。',
  'A close mouth catches no flies. <br>病从口入。',
  'A constant guest is never welcome. <br>常客令人厌。',
  'Actions speak louder than words. <br>事实胜于雄辩。',
  'Adversity leads to prosperity. <br>穷则思变。',
  'Adversity makes a man wise, not rich. <br>逆境出人才。',
  'A fair death honors the whole life. <br>死得其所，流芳百世。',
  'A faithful friend is hard to find. <br>知音难觅。',
  'A fall into a pit, a gain in your wit. <br>吃一堑，长一智。',
  'A fox may grow gray, but never good. <br>江山易改，本性难移。',
  'A friend in need is a friend indeed. <br>患难见真情。',
  'A friend is easier lost than found. <br>得朋友难，失朋友易。',
  'A friend is never known till a man has need. <br>需要之时方知友。',
  'A friend without faults will never be found. <br>没有十全十美的朋友。',
  '"After you" is good manners. <br>“您先请”是礼貌。',
  'A good beginning is half done. <br>良好的开端是成功的一半。',
  'A good beginning makes a good ending. <br>善始者善终。',
  'A good book is a good friend. <br>好书如挚友。',
  'A good book is the best of friends, the same today and forever. <br>一本好书，相伴一生。',
  'A good conscience is a soft pillow. <br>不做亏心事，不怕鬼叫门。',
  'A good fame is better than a good face. <br>美名胜过美貌。',
  'A good husband makes a good wife. <br>夫善则妻贤。',
  'A good medicine tastes bitter. <br>良药苦口。',
  'A good wife health is a man\'s best wealth. <br>妻贤身体好是男人最大的财富。',
  'A great talker is a great liar. <br>说大话者多谎言。',
  'A hedge between keeps friendship green. <br>君子之交淡如水。',
  'A joke never gains an enemy but loses a friend. <br>戏谑不能化敌为友，只能使人失去朋友。',
  'A leopard cannot change its spots. <br>积习难改。',
  'A liar is not believed when he speaks the truth. <br>说谎者即使讲真话也没人相信。',
  'A light heart lives long. <br>静以修身。',
  'A little body often harbors a great soul. <br>浓缩的都是精品。',
  'A little knowledge is a dangerous thing. <br>一知半解，自欺欺人。',
  'A little pot is soon hot. <br>狗肚子盛不得四两油。',
  'All are brave when the enemy flies. <br>敌人逃窜时，人人都成了勇士。',
  'All good things come to an end. <br>天下没有不散的筵席。',
  'All rivers run into sea. <br>海纳百川。',
  'All roads lead to Rome. <br>条条大路通罗马。',
  'All that ends well is well. <br>结果好，就一切都好。',
  'All that glitters is not gold. <br>闪光的不一定都是金子。',
  'All things are difficult before they are easy. <br>凡事总是由难而易。',
  'All work and no play makes Jack a dull boy. <br>只会用功不玩耍，聪明孩子也变傻。',
  'A man becomes learned by asking questions. <br>不耻下问才能有学问。',
  'A man can do no more than he can. <br>凡事都应量力而行。',
  'A man cannot spin and reel at the same time. <br>一心不能二用。',
  'A man is known by his friends. <br>什么人交什么朋友。',
  'A man of words and not of deeds is like a garden full of weeds. <br>光说空话不做事，犹如花园光长刺。',
  'A man without money is no man at all. <br>一分钱难倒英雄汉。',
  'A merry heart goes all the way. <br>心旷神怡，事事顺利。',
  'A miss is as good as a mile. <br>失之毫厘，差之千里。',
  'A mother\'s love never changes. <br>母爱永恒。',
  'An apple a day keeps the doctor away. <br>一天一苹果，不用请医生。',
  'A new broom sweeps clean. <br>新官上任三把火。',
  'An eye for an eye and a tooth for a tooth. <br>以眼还眼，以牙还牙。',
  'An hour in the morning is worth two in the evening. <br>一日之计在于晨。',
  'An old dog cannot learn new tricks. <br>老狗学不出新把戏。',
  'An ounce of luck is better than a pound of wisdom. <br>聪明才智，不如运气。',
  'An ounce of prevention is worth a pound of cure. <br>预防为主，治疗为辅。',
  'A rolling stone gathers no moss. <br>滚石不生苔，转业不聚财。',
  'As a man sows, so he shall reap. <br>种瓜得瓜，种豆得豆。',
  'A single flower does not make a spring. <br>一花独放不是春，百花齐放春满园。',
  'A snow year, a rich year. <br>瑞雪兆丰年。',
  'A sound mind in a sound body. <br>健全的精神寓于健康的身体。',
  'A still tongue makes a wise head. <br>寡言者智。',
  'A stitch in time saves nine. <br>小洞不补，大洞吃苦。',
  'A straight foot is not afraid of a crooked shoe. <br>身正不怕影子斜。',
  'A wise head makes a close mouth. <br>真人不露相，露相非真人。',
  'A word spoken is past recalling. <br>一言既出，驷马难追。',
  'A year\'s plan starts with spring. <br>一年之计在于春。',
  'A young idler, an old beggar. <br>少壮不努力，老大徒伤悲。',
  'Bad news has wings. <br>好事不出门，坏事传千里。',
  'Barking dogs seldom bite. <br>吠犬不咬人。',
  'Beauty lies in the love\'s eyes. <br>情人眼里出西施。',
  'Be swift to hear, slow to speak. <br>听宜敏捷，言宜缓行。',
  'Better late than never. <br>不怕慢，单怕站。',
  'Better to ask the way than go astray. <br>问路总比迷路好。',
  'Between friends all is common. <br>朋友之间不分彼此。',
  'Birds of a feather flock together. <br>物以类聚，人以群分。',
  'Blood is thicker than water. <br>血浓于水。',
  'Blood will have blood. <br>血债血偿。',
  'Books and friends should be few but good. <br>读书如交友，应求少而精。',
  'Business is business. <br>公事公办。',
  'Business is the salt of life. <br>事业是人生的第一需要。',
  'By reading we enrich the mind, by conversation we polish it. <br>读书使人充实，交谈使人精明。',
  'Cannot see the wood for the trees. <br>一叶障目，不见泰山。',
  'Care and diligence bring luck. <br>谨慎和勤奋才能抓住机遇。',
  'Caution is the parent of safety. <br>小心驶得万年船。',
  'Cheats never prosper. <br>骗人发不了财。',
  'Children are what the mothers are. <br>耳濡目染，身教言传。',
  'Choose an author as you choose a friend. <br>择书如择友。',
  'Come what may, heaven won\'t fall. <br>做你的吧，天塌不下来。',
  'Complacency is the enemy of study. <br>学习的敌人是自己的满足。',
  'Confidence in yourself is the first step on the road to success. <br>自信是走向成功的第一步。',
  'Constant dripping wears away a stone. <br>水滴石穿，绳锯木断。',
  'Content is better than riches. <br>知足者常乐。',
  'Count one\'s chickens before they are hatched. <br>蛋未孵先数雏。',
  'Courtesy on one side only lasts not long. <br>来而不往非礼也。',
  'Creep before you walk. <br>循序渐进。',
  'Cry for the moon. <br>海底捞月。',
  'Custom is a second nature. <br>习惯是后天养成的。',
  'Custom makes all things easy. <br>有个好习惯，事事皆不难。',
  'Diamond cuts diamond. <br>强中自有强中手。',
  'Do as the Romans do. <br>入乡随俗。',
  'Do as you would be done by. <br>己所不欲，勿施于人。',
  'Doing is better than saying. <br>与其挂在嘴上，不如落实在行动上。',
  'Do it now. <br>机不可失，时不再来。',
  'Do nothing by halves. <br>凡事不可半途而废。',
  'Don\'t claim to know what you don\'t know. <br>不要不懂装懂。',
  'Don\'t have too many irons in the fire. <br>不要揽事过多。',
  'Don\'t make a mountain out of a molehill. <br>不要小题大做。',
  'Don\'t put off till tomorrow what should be done today. <br>今日事，今日毕。',
  'Don\'t put the cart before the horse. <br>不要本末倒置。',
  'Don\'t trouble trouble until trouble troubles you. <br>不要自找麻烦。',
  'Don\'t try to teach your grandmother to suck eggs. <br>不要班门弄斧。',
  'Do well and have well. <br>善有善报。',
  'Each bird love to hear himself sing. <br>孤芳自赏。',
  'Early to bed and early to rise makes a man healthy, wealthy and wise. <br>早睡早起身体好。',
  'Easier said than done. <br>说得容易，做得难。',
  'Easy come, easy go. <br>来也匆匆，去也匆匆。',
  'Eat to live, but not live to eat. <br>人吃饭是为了活着，但活着不是为了吃饭。',
  'Empty vessels make the greatest sound. <br>实磨无声空磨响，满瓶不动半瓶摇。',
  'Envy has no holidays. <br>忌妒之人无宁日。',
  'Even Homer sometimes nods. <br>智者千虑，必有一失。',
  'Even reckoning makes long friends. <br>亲兄弟，明算账。',
  'Every advantage has its disadvantage. <br>有利必有弊。',
  'Everybody\'s business is nobody\'s business. <br>人人负责，等于没人负责。',
  'Every day is not Sunday. <br>好景不常在。',
  'Every dog has his day. <br>谁都有得意的时候。',
  'Every door may be shut, but death\'s door. <br>人生在世，唯死难逃。',
  'Every heart has its own sorrow. <br>各人有各人的苦恼。',
  'Every little helps a mickle. <br>聚沙成塔，集腋成裘。',
  'Every man for himself, and the devil takes the hindmost. <br>人不为己，天诛地灭。',
  'Every man has his faults. <br>金无足赤，人无完人。',
  'Every man has his hobbyhorse. <br>萝卜青菜，各有所爱。',
  'Every man has his weak side. <br>人人都有弱点。',
  'Every man is the architect of his own fortune. <br>自己的命运自己掌握。',
  'Every minute counts. <br>分秒必争。',
  'Every mother\'s child is handsome. <br>孩子是自己的好。',
  'Every potter praises hit pot. <br>王婆卖瓜，自卖自夸。',
  'Everything is good when new, but friends when old. <br>东西是新的好，朋友是老的亲。',
  'Example is better then percept. <br>说一遍，不如做一遍。',
  'Experience is the father of wisdom and memory the mother. <br>经验是智慧之父，记忆是智慧之母。',
  'Experience must be bought. <br>吃一堑，长一智。',
  'Fact speak louder than words. <br>事实胜于雄辩。',
  'Failure is the mother of success. <br>失败是成功之母。',
  'False friends are worse than bitter enemies. <br>明枪易躲，暗箭难防。',
  'Far from eye, far from heart. <br>眼不见，心不烦。',
  'Far water does not put out near fire. <br>远水救不了近火。',
  'Faults are thick where love is thin. <br>一朝情意淡，样样不顺眼。',
  'Fear always springs from ignorance. <br>恐惧源于无知。',
  'Fields have eyes, and woods have ears. <br>隔墙有耳。',
  'Fire and water have no mercy. <br>水火无情。',
  'Fire is a good servant but a bad master. <br>火是一把双刃剑。',
  'First come, first served. <br>先来后到。',
  'First impressions are half the battle. <br>初次见面，印象最深。',
  'First think and then speak. <br>先想后说。',
  'Fools grow without watering. <br>朽木不可雕。',
  'Fool\'s haste is no speed. <br>欲速则不达。',
  'Fools has fortune. <br>呆人有呆福。',
  'Fools learn nothing from wise men, but wise men learn much from fools. <br>愚者不学无术，智者不耻下问。',
  'Forbidden fruit is sweet. <br>禁果格外香。',
  'Fortune favors those who use their judgement. <br>机遇偏爱善断之人。',
  'Fortune knocks once at least at every man\'s gate. <br>风水轮流转。',
  'Four eyes see more than two. <br>集思广益。',
  'Friends agree best at distance. <br>朋友之间也会保持距离。',
  'Friends are thieves of time. <br>朋友是时间的窃贼。',
  'Friends must part. <br>再好的朋友也有分手的时候。',
  'Genius is nothing but labor and diligence. <br>天才不过是勤奋而已。',
  'Give a dog a bad name and hang him. <br>众口铄金，积毁销骨。',
  'God helps those who help themselves. <br>自助者天助。',
  'Gold will not buy anything. <br>黄金并非万能。',
  'Good for good is natural, good for evil is manly. <br>以德报德是常理，以德报怨大丈夫。',
  'Good health is over wealth. <br>健康是最大的财富。',
  'Good medicine for health tastes bitter to the mouth. <br>良药苦口利于病。',
  'Good watch prevents misfortune. <br>谨慎消灾。',
  'Great barkers are no biters. <br>好狗不挡道。',
  'Great hopes make great man. <br>伟大的抱负造就伟大的人物。',
  'Great minds think alike. <br>英雄所见略同。',
  'Great men have great faults. <br>英雄犯大错误。',
  'Great men\'s sons seldom do well. <br>富不过三代。',
  'Great trees are good for nothing but shade. <br>大树底下好乘凉。',
  'Great wits have short memories. <br>贵人多忘事。',
  'Greedy folks have long arms. <br>心贪手长。',
  'Guilty consciences make men cowards. <br>做贼心虚。',
  'Habit cures habit. <br>心病还需心药医。',
  'Handsome is he who does handsomely. <br>行为漂亮才算美。',
  'Happiness takes no account of time. <br>欢乐不觉时光过。',
  'Happy is he who owes nothing. <br>要想活得痛快，身上不能背债。',
  'Happy is the man who learns from the misfortunes of others. <br>吸取他人教训，自己才会走运。',
  'Harm set, harm get. <br>害人害己。',
  'Hasty love, soon cold. <br>一见钟情难维久。',
  'Health is better than wealth. <br>健康胜过财富。',
  'Health is happiness. <br>健康就是幸福。',
  'Hear all parties. <br>兼听则明。',
  'Heaven never helps the man who will not act. <br>自己不动，叫天何用。',
  'He is a fool that forgets himself. <br>愚者忘乎所以。',
  'He is a good friend that speaks well of us behind our backs. <br>背后说好话，才是真朋友。',
  'He is a wise man who speaks little. <br>聪明不是挂在嘴上。',
  'He is lifeless that is faultless. <br>只有死人才不犯错误。',
  'He is not fit to command others that cannot command himself. <br>正人先正己。',
  'He is not laughed at that laughs at himself first. <br>自嘲者不会让人见笑。',
  'He is wise that is honest. <br>诚实者最明智。',
  'He knows most who speaks least. <br>大智若愚。',
  'He laughs best who laughs last. <br>谁笑到最后，谁笑得最好。',
  'He sets the fox to keep the geese. <br>引狼入室。',
  'He that climbs high falls heavily. <br>爬得越高，摔得越重。',
  'He that will not work shall not eat. <br>不劳动者不得食。',
  'He who does not advance loses ground. <br>逆水行舟，不进则退。',
  'He who makes constant complaint gets little compassion. <br>经常诉苦，没人同情。',
  'He who makes no mistakes makes nothing. <br>想不犯错误，就一事无成。',
  'He who risks nothing gains nothing. <br>收获与风险并存。',
  'History repeats itself. <br>历史往往重演。',
  'Honesty is the best policy. <br>做人诚信为本。',
  'Hope for the best, but prepare for the worst. <br>抱最好的愿望，做最坏的打算。',
  'I cannot be your friend and your flatterer too. <br>朋友不能阿谀奉承。',
  'If a man deceives me once, shame on him, if he deceives me twice, shame on me. <br>上当一回头，再多就可耻。',
  'If you make yourself an ass, don\'t complain if people ride you. <br>人善被人欺，马善被人骑。',
  'If your ears glow, someone is talking of you. <br>耳朵发烧，有人念叨。',
  'If you run after two hares, you will catch neither. <br>脚踏两条船，必定落空。',
  'If you sell the cow, you sell her milk too. <br>杀鸡取卵。',
  'If you venture nothing, you will have nothing. <br>不入虎穴，焉得虎子。',
  'If you want knowledge, you must toil for it. <br>要想求知，就得吃苦。',
  'Industry is the parent of success. <br>勤奋是成功之母。',
  'It is better to die when life is a disgrace. <br>宁为玉碎，不为瓦全。',
  'It is easier to get money than to keep it. <br>挣钱容易攒钱难。',
  'It is easy to be wise after the event. <br>事后诸葛亮好当。',
  'It is easy to open a shop but hard to keep it always open. <br>创业容易守业难。',
  'It is hard to please all. <br>众口难调。',
  'It is never too old to learn. <br>活到老，学到老。',
  'It is no use crying over spilt milk. <br>覆水难收。',
  'It is the first step that costs troublesome. <br>万事开头难。',
  'It is the unforeseen that always happens. <br>天有不测风云，人有旦夕祸福。',
  'It is too late to grieve when the chance is past. <br>坐失良机，后悔已迟。',
  'It never rains but it pours. <br>不鸣则已，一鸣惊人。',
  'It takes three generations to make a gentleman. <br>十年树木，百年树人。',
  'Jack of all trades and master of none. <br>门门精通，样样稀松。',
  'Judge not from appearances. <br>人不可貌相，海不可斗量。',
  'Justice has long arms. <br>天网恢恢，疏而不漏。',
  'Keep good men company and you shall be of the number. <br>近朱者赤，近墨者黑。',
  'Kill two birds with one stone. <br>一箭双雕。',
  'Kings go mad, and the people suffer for it. <br>君王发狂，百姓遭殃。',
  'Kings have long arms. <br>普天之下，莫非王土。',
  'Knowledge is power. <br>知识就是力量。',
  'Knowledge makes humble, ignorance makes proud. <br>博学使人谦逊，无知使人骄傲。',
  'Learn and live. <br>活着，为了学习。',
  'Learning makes a good man better and ill man worse. <br>好人越学越好，坏人越学越坏。',
  'Learn not and know not. <br>不学无术。',
  'Learn to walk before you run. <br>先学走，再学跑。',
  'Let bygones be bygones. <br>过去的就让它过去吧。',
  'Let sleeping dogs lie. <br>别惹麻烦。',
  'Let the cat out of the bag. <br>泄漏天机。',
  'Lies can never changes fact. <br>谎言终究是谎言。',
  'Lies have short legs. <br>谎言站不长。',
  'Life is but a span. <br>人生苦短。',
  'Life is half spent before we know what it is. <br>人过半生，方知天命。',
  'Life is not all roses. <br>人生并不是康庄大道。',
  'Life without a friend is death. <br>没有朋友，虽生犹死。',
  'Like a rat in a hole. <br>瓮中之鳖。',
  'Like author, like book. <br>文如其人。',
  'Like father, like son. <br>有其父必有其子。',
  'Like for like. <br>一报还一报。',
  'Like knows like. <br>惺惺相惜。',
  'Like mother, like daughter. <br>有其母必有其女。',
  'Like teacher, like pupil. <br>什么样的老师教什么样的学生。',
  'Like tree, like fruit. <br>羊毛出在羊身上。',
  'Little things amuse little minds. <br>小人无大志。',
  'Look before you leap. <br>摸清情况再行动。',
  'Lookers-on see more than players. <br>当局者迷，旁观者清。',
  'Losers are always in the wrong. <br>胜者为王，败者为寇。',
  'Lost time is never found again. <br>岁月既往，一去不回。',
  'Love at first sight. <br>一见钟情。',
  'Love cannot be compelled. <br>爱情不能强求。',
  'Love is blind. <br>爱情是盲目的。',
  'Love is full of trouble. <br>爱情充满烦恼。',
  'Love is never without jealousy. <br>没有妒忌就没有爱情。',
  'Love me, love my dog. <br>爱屋及乌。',
  'Make hay while the sun shines. <br>良机勿失。',
  'Make your enemy your friend. <br>化敌为友。',
  'Man is the soul of the universe. <br>人是万物之灵。',
  'Man proposes, God disposes. <br>谋事在人，成事在天。',
  'Many hands make light work. <br>众人拾柴火焰高。',
  'Many heads are better than one. <br>三个臭皮匠，赛过诸葛亮。',
  'Many things grow in the garden that were never sown there. <br>有心栽花花不发，无心插柳柳成荫。',
  'Measure for measure. <br>针锋相对。',
  'Misfortunes never come alone. <br>祸不单行。',
  'Misfortune tests the sincerity of friends. <br>患难见真情。',
  'Money isn\'t everything. <br>钱不是万能的。',
  'Murder will out. <br>纸包不住火。',
  'My son is my son till he has got him a wife, but my daughter is my daughter all the days of her life. <br>儿子婚前是儿子，女儿终生是女儿。',
  'Nature is the true law. <br>天行有常，不为尧存，不为桀亡。',
  'Necessity is the mother of invention. <br>需要是发明的动力。',
  'Never fish in trouble water. <br>不要混水摸鱼。',
  'Never judge from appearances. <br>不可以貌取人。',
  'Never say die. <br>永不言败。',
  'Never too old to learn, never too late to turn. <br>亡羊补牢，为时未晚。',
  'New wine in old bottles. <br>旧瓶装新酒。',
  'No cross, no crown. <br>不经历风雨，怎么见彩虹。',
  'No garden without its weeds. <br>没有不长草的园子。',
  'No living man all things can. <br>世上没有万事通。',
  'No man can do two things at once. <br>一心不可二用。',
  'No man is born wise or learned. <br>没有生而知之者。',
  'No man is content. <br>人心不足蛇吞象。',
  'No man is wise at all times. <br>聪明一世，糊涂一时。',
  'None are so blind as those who won\'t see. <br>视而不见。',
  'None are so deaf as those who won\'t hear. <br>充耳不闻。',
  'No news is good news. <br>没有消息就是好消息。',
  'No one can call back yesterday. <br>昨日不会重现。',
  'No pains, no gains. <br>没有付出就没有收获。',
  'No pleasure without pain. <br>没有苦就没有乐。',
  'No rose without a thorn. <br>没有不带刺的玫瑰。',
  'No sweet without sweat. <br>先苦后甜。',
  'No smoke without fire. <br>无风不起浪。',
  'Nothing brave, nothing have. <br>不入虎穴，焉得虎子。',
  'Nothing dries sooner than a tear. <br>眼泪干得最快。',
  'Nothing in the world is difficult for one who sets his mind to it. <br>世上无难事，只怕有心人。',
  'Nothing is difficult to the man who will try. <br>世上无难事，只要肯登攀。',
  'Nothing seek, nothing find. <br>没有追求就没有收获。',
  'Nothing is so necessary for travelers as languages. <br>外出旅行，语言最要紧。',
  'Nothing is to be got without pains but poverty. <br>世上唯有贫穷可以不劳而获。',
  'Not to advance is to go back. <br>不进则退。',
  'Not to know what happened before one was born is always to be a child. <br>不懂世故，幼稚可笑。',
  'No way is impossible to courage. <br>勇者无惧。',
  'Obedience is the first duty of a soldier. <br>军人以服从命令为天职。',
  'Observation is the best teacher. <br>观察是最好的老师。',
  'Offense is the best defense. <br>进攻是最好的防御。',
  'Old friends and old wines are best. <br>陈酒味醇，老友情深。',
  'Old sin makes new shame. <br>一失足成千古恨。',
  'Once a man and twice a child. <br>一次老，两次小。',
  'Once a thief, always a thief. <br>偷盗一次，做贼一世。',
  'Once bitten, twice shy. <br>一朝被蛇咬，十年怕井绳。',
  'One boy is a boy, two boys half a boy, three boys no boy. <br>一个和尚挑水喝，两个和尚抬水喝，三个和尚没水喝。',
  'One cannot put back the clock. <br>时钟不能倒转。',
  'One eyewitness is better than ten hearsays. <br>百闻不如一见。',
  'One false move may lose the game. <br>一着不慎，满盘皆输。',
  'One good turn deserves another. <br>行善积德。',
  'One hour today is worth two tomorrow. <br>争分夺秒效率高。',
  'One man\'s fault is other man\'s lesson. <br>前车之鉴。',
  'One never loses anything by politeness. <br>讲礼貌不吃亏。',
  'One swallow does not make a summer. <br>一燕不成夏。',
  'One\'s words reflect one\'s thinking. <br>言为心声。',
  'Out of debt, out of danger. <br>无债一身轻。',
  'Out of office, out of danger. <br>无官一身轻。',
  'Out of sight, out of mind. <br>眼不见，心为静。',
  'Patience is the best remedy. <br>忍耐是良药。',
  'Penny wise, pound foolish. <br>贪小便宜吃大亏。',
  'Plain dealing is praised more than practiced. <br>正大光明者，说到的多，做到的少。',
  'Please the eye and plague the heart. <br>贪图一时快活，必然留下隐祸。',
  'Pleasure comes through toil. <br>苦尽甘来。',
  'Pour water into a sieve. <br>竹篮子打水一场空。',
  'Practice makes perfect. <br>熟能生巧。',
  'Praise is not pudding. <br>恭维话不能当饭吃。',
  'Praise makes good men better, and bad men worse. <br>好人越夸越好，坏人越夸越糟。',
  'Prefer loss to unjust gain. <br>宁可吃亏，不贪便宜。',
  'Prevention is better than cure. <br>预防胜于治疗。',
  'Pride goes before, and shame comes after. <br>骄傲使人落后。',
  'Promise is debt. <br>一诺千金。',
  'Proverbs are the daughters of daily experience. <br>谚语是日常经验的结晶。',
  'Pull the chestnut out of fire. <br>火中取栗。',
  'Put the cart before the horse. <br>本末倒置。',
  'Put your shoulder to the wheel. <br>鼎力相助。',
  'Reading enriches the mind. <br>开卷有益。',
  'Reading is to the mind while exercise to the body. <br>读书健脑，运动强身。',
  'Respect yourself, or no one else will respect you. <br>要人尊敬，必须自重。',
  'Rome is not built in a day. <br>冰冻三尺，非一日之寒。',
  'Saying is one thing and doing another. <br>言行不一。',
  'Seeing is believing. <br>眼见为实。',
  'Seek the truth from facts. <br>实事求是。',
  'Send a wise man on an errand, and say nothing to him. <br>智者当差，不用交代。',
  'Set a thief to catch a thief. <br>以贼捉贼。',
  'Short accounts make long friends. <br>好朋友勤算账。',
  'Something is better than nothing. <br>聊胜于无。',
  'Soon learn, soon forgotten. <br>学得快，忘得快。',
  'Soon ripe, soon rotten. <br>熟得快，烂得快。',
  'Speech is silver, silence is gold. <br>能言是银，沉默是金。',
  'Still water run deep. <br>静水常深。',
  'Strike the iron while it is hot. <br>趁热打铁。',
  'Success belongs to the persevering. <br>坚持就是胜利。',
  'Take things as they come. <br>既来之，则安之。',
  'Talking mends no holes. <br>空谈无补。',
  'Talk of the devil and he will appear. <br>说曹操，曹操就到。',
  'Tall trees catch much wind. <br>树大招风。',
  'Teach others by your example. <br>躬亲示范。',
  'The best hearts are always the bravest. <br>无私者无畏。',
  'The best man stumbles. <br>伟人也有犯错时。',
  'The cat shuts its eyes when stealing. <br>掩耳盗铃。',
  'The danger past and God forgotten. <br>过河拆桥。',
  'The darkest hour is nearest the dawn. <br>黎明前的黑暗。',
  'The darkest place is under the candlestick. <br>烛台底下最暗。',
  'The devil knows many things because he is old. <br>老马识途。',
  'The devil sometimes speaks the truth. <br>魔鬼有时也会说真话。',
  'The die is cast. <br>木已成舟。',
  'The early bird catches the worm. <br>早起的鸟儿有虫吃。',
  'The end justifies the means. <br>只要目的正当，可以不择手段。',
  'The end makes all equal. <br>死亡面前，人人平等。',
  'The eye is bigger than the belly. <br>贪多嚼不烂。',
  'The farthest way about is the nearest way home. <br>抄近路反而绕远路。',
  'The finest diamond must be cut. <br>玉不琢，不成器。',
  'The fire is the test of gold, adversity of strong man. <br>烈火验真金，艰难磨意志。',
  'The first step is the only difficulty. <br>迈出第一步是最艰难的。',
  'The fox knew too much, that\'s how he lost his tail. <br>机关算尽太聪明，反误了卿卿性命。',
  'The fox preys farthest from home. <br>兔子不吃窝边草。',
  'The frog in the well knows nothing of the great ocean. <br>坐井观天。',
  'The grass is greener on the other side. <br>这山望着那山高。',
  'The greatest talkers are always least doers. <br>语言的巨人总是行动的矮子。',
  'The higher up, the greater the fall. <br>爬得高，摔得惨。',
  'The leopard cannot change its spots. <br>本性难移。',
  'The more noble, the more humble. <br>人越高尚，越谦虚。',
  'The more wit, the less courage. <br>初生牛犊不怕虎。',
  'The outsider sees the most of the game. <br>旁观者清。',
  'The pen is mightier than the sword. <br>笔能杀人。',
  'The pot calls the kettle black. <br>五十步笑百步。',
  'There are spots in the sun. <br>太阳也有黑点。',
  'There are two sides to every question. <br>问题皆有两面。',
  'There is a skeleton in the cupboard. <br>家家有本难念的经。',
  'There is kindness to be found everywhere. <br>人间处处有温情。',
  'There is no general rule without some exception. <br>任何法规均有例外。',
  'There is no medicine against death. <br>没有长生不老药。',
  'There is no place like home. <br>金窝银窝不如咱的狗窝。',
  'There is no royal road to learning. <br>书山有路勤为径，学海无涯苦作舟。',
  'The style is the man. <br>字如其人。',
  'The tongue is not steel, yet it cuts. <br>人言可畏。',
  'The water that bears the boat is the same that swallows it up. <br>水能载舟，亦能覆舟。',
  'The wise man knows he knows nothing, the fool thinks he knows all. <br>清者自清，浊者自浊。',
  'The wolf has a winning game when the shepherds quarrel. <br>螳螂捕蝉，黄雀在后。',
  'The world is a ladder for some to go up and others to go down. <br>世界如阶梯，有人上有人下。',
  'The world is but a little place, after all. <br>海内存知己，天涯若比邻。',
  'Think twice before you do. <br>三思而后行。',
  'Things at the worst will mend. <br>否极泰来。',
  'Time and tide wait for no man. <br>时不我待。',
  'Time cures all things. <br>时间是医治一切创伤的良药。',
  'Time flies. <br>光阴似箭。',
  'Time is money. <br>时间就是金钱。',
  'Time lost cannot be won again. <br>时光流逝，不可复得。',
  'Time past cannot be called back again. <br>时间不能倒流。',
  'Time tries all. <br>路遥知马力，日久见人心。',
  'Tit for tat is fair play. <br>人不犯我，我不犯人；人若犯我，我必犯人。',
  'To err is human. <br>人非圣贤，孰能无过。',
  'To know everything is to know nothing. <br>什么都知道，一如什么都不知道。',
  'To know oneself is true progress. <br>人贵有自知之明。',
  'Tomorrow never comes. <br>我生待明日，万事成蹉跎。',
  'Too much familiarity breeds contempt. <br>过分熟悉会使人互不服气。',
  'Too much knowledge makes the head bald. <br>学问太多催人老。',
  'Too much liberty spills all. <br>自由放任，一事无成。',
  'Too much praise is a burden. <br>过多夸奖，反成负担。',
  'To save time is to lengthen life. <br>节约时间就是延长生命。',
  'Touch pitch, and you will be defiled. <br>常在河边走，哪有不湿鞋。',
  'Troubles never come singly. <br>福无双至，祸不单行。',
  'Truth never grows old. <br>真理永存。',
  'Turn over a new leaf. <br>洗心革面，改过自新。',
  'Two dogs strive for a bone, and a third runs away with it. <br>鹬蚌相争，渔翁得利。',
  'Two heads are better than one. <br>一个好汉三个帮。',
  'Two of a trade seldom agree. <br>同行是冤家。',
  'Two wrongs do not make a right. <br>别人错了，不等于你对了。',
  'Unity is strength. <br>团结就是力量。',
  'Unpleasant advice is a good medicine. <br>忠言逆耳利于行。',
  'Until all is over one\'s ambition never dies. <br>不到黄河心不死。',
  'Venture a small fish to catch a great one. <br>吃小亏占大便宜。',
  'Virtue is fairer far than beauty. <br>美德远远胜过美貌。',
  'Walls have ears. <br>小心隔墙有耳。',
  'Wash your dirty linen at home. <br>家丑不可外扬。',
  'Water dropping day by day wears the hardest rock away. <br>滴水穿石。',
  'Wealth is nothing without health. <br>失去健康，钱再多也没用。',
  'We know not what is good until we have lost it. <br>好东西，失去了才明白。',
  'Well begun is half done. <br>好的开始，是成功的一半。',
  'We never know the worth of water till the well is dry. <br>井干方知水可贵。',
  'We shall never have friends if we expect to find them without fault. <br>欲求完美无缺的朋友必然成为孤家寡人。',
  'We should never remember the benefits we have offered nor forget the favor received. <br>自己的好事别去提，别人的恩惠要铭记。',
  'Wet behind the ears. <br>乳臭未干。',
  'Whatever you do, do with all your might. <br>不管做什么，都要一心一意。',
  'What is learned in the cradle is carried to the grave. <br>儿时所学，终生难忘。',
  'What\'s done cannot be undone. <br>生米煮成熟饭了。',
  'What\'s lost is lost. <br>失者不可复得。',
  'What we do willingly is easy. <br>愿者不难。',
  'When in Rome, do as the Romans do. <br>入国问禁，入乡随俗。',
  'When everybody\'s somebody then nobody\'s anybody. <br>人人都伟大，世间没豪杰。',
  'When sorrow is asleep, wake it not. <br>伤心旧事别重提。',
  'When sorrows come, they come not single spies, but in battalions. <br>新仇旧恨，齐上心头。',
  'When the fox preaches, take care of your geese. <br>黄鼠狼给鸡拜年，没安好心。',
  'When wine is in truth, wit is out. <br>酒后吐真言。',
  'Where there is a will, there is a way. <br>有志者事竟成。',
  'Where there is life, there is hope. <br>留得青山在，不怕没柴烧。',
  'Where there is smoke, there is fire. <br>事出有因。',
  'While the priest climbs a post, the devil climbs ten. <br>道高一尺，魔高一丈。',
  'Who chatters to you, will chatter of you. <br>搬弄口舌者必是小人。',
  'Whom the gods love die young. <br>好人不长命。',
  'Wise man have their mouths in their hearts, fools have their hearts in their mouths. <br>智者嘴在心里，愚者心在嘴里。',
  'Work makes the workman. <br>勤工出巧匠。',
  'You cannot burn the candle at both ends. <br>蜡烛不能两头点，精力不可过分耗。',
  'You cannot eat your cake and have it. <br>鱼与熊掌，不可得兼。',
  'You can take a horse to the water but you cannot make him drink. <br>强扭的瓜不甜。',
  'You may know by a handful the whole sack. <br>由一斑可知全貌。',
  'You never know what you can till you try. <br>是驴子是马，拉出来遛遛)'
];
