var bullets = [
  'A bad beginning makes a bad ending.',
  '不善始者不善终。',
  'A bad thing never dies.',
  '遗臭万年。',
  'A bad workman always blames his tools.',
  '不会撑船怪河弯。',
  'A bird in the hand is worth than two in the bush.',
  '一鸟在手胜过双鸟在林。',
  'A boaster and a liar are cousins-german.',
  '吹牛与说谎本是同宗。',
  'A bully is always a coward.',
  '色厉内荏。',
  'A burden of one\'s choice is not felt.',
  '爱挑的担子不嫌重。',
  'A candle lights others and consumes itself.',
  '蜡烛照亮别人，却毁灭了自己。',
  'A cat has 9 lives.',
  '猫有九条命。',
  'A cat may look at a king.',
  '人人平等。',
  'A close mouth catches no flies.',
  '病从口入。',
  'A constant guest is never welcome.',
  '常客令人厌。',
  'Actions speak louder than words.',
  '事实胜于雄辩。',
  'Adversity leads to prosperity.',
  '穷则思变。',
  'Adversity makes a man wise, not rich.',
  '逆境出人才。',
  'A fair death honors the whole life.',
  '死得其所，流芳百世。',
  'A faithful friend is hard to find.',
  '知音难觅。',
  'A fall into a pit, a gain in your wit.',
  '吃一堑，长一智。',
  'A fox may grow gray, but never good.',
  '江山易改，本性难移。',
  'A friend in need is a friend indeed.',
  '患难见真情。',
  'A friend is easier lost than found.',
  '得朋友难，失朋友易。',
  'A friend is never known till a man has need.',
  '需要之时方知友。',
  'A friend without faults will never be found.',
  '没有十全十美的朋友。',
  '"After you" is good manners.',
  '“您先请”是礼貌。',
  'A good beginning is half done.',
  '良好的开端是成功的一半。',
  'A good beginning makes a good ending.',
  '善始者善终。',
  'A good book is a good friend.',
  '好书如挚友。',
  'A good book is the best of friends, the same today and forever.',
  '一本好书，相伴一生。',
  'A good conscience is a soft pillow.',
  '不做亏心事，不怕鬼叫门。',
  'A good fame is better than a good face.',
  '美名胜过美貌。',
  'A good husband makes a good wife.',
  '夫善则妻贤。',
  'A good medicine tastes bitter.',
  '良药苦口。',
  'A good wife health is a man\'s best wealth.',
  '妻贤身体好是男人最大的财富。',
  'A great talker is a great liar.',
  '说大话者多谎言。',
  'A hedge between keeps friendship green.',
  '君子之交淡如水。',
  'A joke never gains an enemy but loses a friend.',
  '戏谑不能化敌为友，只能使人失去朋友。',
  'A leopard cannot change its spots.',
  '积习难改。',
  'A liar is not believed when he speaks the truth.',
  '说谎者即使讲真话也没人相信。',
  'A light heart lives long.',
  '静以修身。',
  'A little body often harbors a great soul.',
  '浓缩的都是精品。',
  'A little knowledge is a dangerous thing.',
  '一知半解，自欺欺人。',
  'A little pot is soon hot.',
  '狗肚子盛不得四两油。',
  'All are brave when the enemy flies.',
  '敌人逃窜时，人人都成了勇士。',
  'All good things come to an end.',
  '天下没有不散的筵席。',
  'All rivers run into sea.',
  '海纳百川。',
  'All roads lead to Rome.',
  '条条大路通罗马。',
  'All that ends well is well.',
  '结果好，就一切都好。',
  'All that glitters is not gold.',
  '闪光的不一定都是金子。',
  'All things are difficult before they are easy.',
  '凡事总是由难而易。',
  'All work and no play makes Jack a dull boy.',
  '只会用功不玩耍，聪明孩子也变傻。',
  'A man becomes learned by asking questions.',
  '不耻下问才能有学问。',
  'A man can do no more than he can.',
  '凡事都应量力而行。',
  'A man cannot spin and reel at the same time.',
  '一心不能二用。',
  'A man is known by his friends.',
  '什么人交什么朋友。',
  'A man of words and not of deeds is like a garden full of weeds.',
  '光说空话不做事，犹如花园光长刺。',
  'A man without money is no man at all.',
  '一分钱难倒英雄汉。',
  'A merry heart goes all the way.',
  '心旷神怡，事事顺利。',
  'A miss is as good as a mile.',
  '失之毫厘，差之千里。',
  'A mother\'s love never changes.',
  '母爱永恒。',
  'An apple a day keeps the doctor away.',
  '一天一苹果，不用请医生。',
  'A new broom sweeps clean.',
  '新官上任三把火。',
  'An eye for an eye and a tooth for a tooth.',
  '以眼还眼，以牙还牙。',
  'An hour in the morning is worth two in the evening.',
  '一日之计在于晨。',
  'An old dog cannot learn new tricks.',
  '老狗学不出新把戏。',
  'An ounce of luck is better than a pound of wisdom.',
  '聪明才智，不如运气。',
  'An ounce of prevention is worth a pound of cure.',
  '预防为主，治疗为辅。',
  'A rolling stone gathers no moss.',
  '滚石不生苔，转业不聚财。',
  'As a man sows, so he shall reap.',
  '种瓜得瓜，种豆得豆。',
  'A single flower does not make a spring.',
  '一花独放不是春，百花齐放春满园。',
  'A snow year, a rich year.',
  '瑞雪兆丰年。',
  'A sound mind in a sound body.',
  '健全的精神寓于健康的身体。',
  'A still tongue makes a wise head.',
  '寡言者智。',
  'A stitch in time saves nine.',
  '小洞不补，大洞吃苦。',
  'A straight foot is not afraid of a crooked shoe.',
  '身正不怕影子斜。',
  'A wise head makes a close mouth.',
  '真人不露相，露相非真人。',
  'A word spoken is past recalling.',
  '一言既出，驷马难追。',
  'A year\'s plan starts with spring.',
  '一年之计在于春。',
  'A young idler, an old beggar.',
  '少壮不努力，老大徒伤悲。',
  'Bad news has wings.',
  '好事不出门，坏事传千里。',
  'Barking dogs seldom bite.',
  '吠犬不咬人。',
  'Beauty lies in the love\'s eyes.',
  '情人眼里出西施。',
  'Be swift to hear, slow to speak.',
  '听宜敏捷，言宜缓行。',
  'Better late than never.',
  '不怕慢，单怕站。',
  'Better to ask the way than go astray.',
  '问路总比迷路好。',
  'Between friends all is common.',
  '朋友之间不分彼此。',
  'Birds of a feather flock together.',
  '物以类聚，人以群分。',
  'Blood is thicker than water.',
  '血浓于水。',
  'Blood will have blood.',
  '血债血偿。',
  'Books and friends should be few but good.',
  '读书如交友，应求少而精。',
  'Business is business.',
  '公事公办。',
  'Business is the salt of life.',
  '事业是人生的第一需要。',
  'By reading we enrich the mind, by conversation we polish it.',
  '读书使人充实，交谈使人精明。',
  'Cannot see the wood for the trees.',
  '一叶障目，不见泰山。',
  'Care and diligence bring luck.',
  '谨慎和勤奋才能抓住机遇。',
  'Caution is the parent of safety.',
  '小心驶得万年船。',
  'Cheats never prosper.',
  '骗人发不了财。',
  'Children are what the mothers are.',
  '耳濡目染，身教言传。',
  'Choose an author as you choose a friend.',
  '择书如择友。',
  'Come what may, heaven won\'t fall.',
  '做你的吧，天塌不下来。',
  'Complacency is the enemy of study.',
  '学习的敌人是自己的满足。',
  'Confidence in yourself is the first step on the road to success.',
  '自信是走向成功的第一步。',
  'Constant dripping wears away a stone.',
  '水滴石穿，绳锯木断。',
  'Content is better than riches.',
  '知足者常乐。',
  'Count one\'s chickens before they are hatched.',
  '蛋未孵先数雏。',
  'Courtesy on one side only lasts not long.',
  '来而不往非礼也。',
  'Creep before you walk.',
  '循序渐进。',
  'Cry for the moon.',
  '海底捞月。',
  'Custom is a second nature.',
  '习惯是后天养成的。',
  'Custom makes all things easy.',
  '有个好习惯，事事皆不难。',
  'Diamond cuts diamond.',
  '强中自有强中手。',
  'Do as the Romans do.',
  '入乡随俗。',
  'Do as you would be done by.',
  '己所不欲，勿施于人。',
  'Doing is better than saying.',
  '与其挂在嘴上，不如落实在行动上。',
  'Do it now.',
  '机不可失，时不再来。',
  'Do nothing by halves.',
  '凡事不可半途而废。',
  'Don\'t claim to know what you don\'t know.',
  '不要不懂装懂。',
  'Don\'t have too many irons in the fire.',
  '不要揽事过多。',
  'Don\'t make a mountain out of a molehill.',
  '不要小题大做。',
  'Don\'t put off till tomorrow what should be done today.',
  '今日事，今日毕。',
  'Don\'t put the cart before the horse.',
  '不要本末倒置。',
  'Don\'t trouble trouble until trouble troubles you.',
  '不要自找麻烦。',
  'Don\'t try to teach your grandmother to suck eggs.',
  '不要班门弄斧。',
  'Do well and have well.',
  '善有善报。',
  'Each bird love to hear himself sing.',
  '孤芳自赏。',
  'Early to bed and early to rise makes a man healthy, wealthy and wise.',
  '早睡早起身体好。',
  'Easier said than done.',
  '说得容易，做得难。',
  'Easy come, easy go.',
  '来也匆匆，去也匆匆。',
  'Eat to live, but not live to eat.',
  '人吃饭是为了活着，但活着不是为了吃饭。',
  'Empty vessels make the greatest sound.',
  '实磨无声空磨响，满瓶不动半瓶摇。',
  'Envy has no holidays.',
  '忌妒之人无宁日。',
  'Even Homer sometimes nods.',
  '智者千虑，必有一失。',
  'Even reckoning makes long friends.',
  '亲兄弟，明算账。',
  'Every advantage has its disadvantage.',
  '有利必有弊。',
  'Everybody\'s business is nobody\'s business.',
  '人人负责，等于没人负责。',
  'Every day is not Sunday.',
  '好景不常在。',
  'Every dog has his day.',
  '谁都有得意的时候。',
  'Every door may be shut, but death\'s door.',
  '人生在世，唯死难逃。',
  'Every heart has its own sorrow.',
  '各人有各人的苦恼。',
  'Every little helps a mickle.',
  '聚沙成塔，集腋成裘。',
  'Every man for himself, and the devil takes the hindmost.',
  '人不为己，天诛地灭。',
  'Every man has his faults.',
  '金无足赤，人无完人。',
  'Every man has his hobbyhorse.',
  '萝卜青菜，各有所爱。',
  'Every man has his weak side.',
  '人人都有弱点。',
  'Every man is the architect of his own fortune.',
  '自己的命运自己掌握。',
  'Every minute counts.',
  '分秒必争。',
  'Every mother\'s child is handsome.',
  '孩子是自己的好。',
  'Every potter praises hit pot.',
  '王婆卖瓜，自卖自夸。',
  'Everything is good when new, but friends when old.',
  '东西是新的好，朋友是老的亲。',
  'Example is better then percept.',
  '说一遍，不如做一遍。',
  'Experience is the father of wisdom and memory the mother.',
  '经验是智慧之父，记忆是智慧之母。',
  'Experience must be bought.',
  '吃一堑，长一智。',
  'Fact speak louder than words.',
  '事实胜于雄辩。',
  'Failure is the mother of success.',
  '失败是成功之母。',
  'False friends are worse than bitter enemies.',
  '明枪易躲，暗箭难防。',
  'Far from eye, far from heart.',
  '眼不见，心不烦。',
  'Far water does not put out near fire.',
  '远水救不了近火。',
  'Faults are thick where love is thin.',
  '一朝情意淡，样样不顺眼。',
  'Fear always springs from ignorance.',
  '恐惧源于无知。',
  'Fields have eyes, and woods have ears.',
  '隔墙有耳。',
  'Fire and water have no mercy.',
  '水火无情。',
  'Fire is a good servant but a bad master.',
  '火是一把双刃剑。',
  'First come, first served.',
  '先来后到。',
  'First impressions are half the battle.',
  '初次见面，印象最深。',
  'First think and then speak.',
  '先想后说。',
  'Fools grow without watering.',
  '朽木不可雕。',
  'Fool\'s haste is no speed.',
  '欲速则不达。',
  'Fools has fortune.',
  '呆人有呆福。',
  'Fools learn nothing from wise men, but wise men learn much from fools.',
  '愚者不学无术，智者不耻下问。',
  'Forbidden fruit is sweet.',
  '禁果格外香。',
  'Fortune favors those who use their judgement.',
  '机遇偏爱善断之人。',
  'Fortune knocks once at least at every man\'s gate.',
  '风水轮流转。',
  'Four eyes see more than two.',
  '集思广益。',
  'Friends agree best at distance.',
  '朋友之间也会保持距离。',
  'Friends are thieves of time.',
  '朋友是时间的窃贼。',
  'Friends must part.',
  '再好的朋友也有分手的时候。',
  'Genius is nothing but labor and diligence.',
  '天才不过是勤奋而已。',
  'Give a dog a bad name and hang him.',
  '众口铄金，积毁销骨。',
  'God helps those who help themselves.',
  '自助者天助。',
  'Gold will not buy anything.',
  '黄金并非万能。',
  'Good for good is natural, good for evil is manly.',
  '以德报德是常理，以德报怨大丈夫。',
  'Good health is over wealth.',
  '健康是最大的财富。',
  'Good medicine for health tastes bitter to the mouth.',
  '良药苦口利于病。',
  'Good watch prevents misfortune.',
  '谨慎消灾。',
  'Great barkers are no biters.',
  '好狗不挡道。',
  'Great hopes make great man.',
  '伟大的抱负造就伟大的人物。',
  'Great minds think alike.',
  '英雄所见略同。',
  'Great men have great faults.',
  '英雄犯大错误。',
  'Great men\'s sons seldom do well.',
  '富不过三代。',
  'Great trees are good for nothing but shade.',
  '大树底下好乘凉。',
  'Great wits have short memories.',
  '贵人多忘事。',
  'Greedy folks have long arms.',
  '心贪手长。',
  'Guilty consciences make men cowards.',
  '做贼心虚。',
  'Habit cures habit.',
  '心病还需心药医。',
  'Handsome is he who does handsomely.',
  '行为漂亮才算美。',
  'Happiness takes no account of time.',
  '欢乐不觉时光过。',
  'Happy is he who owes nothing.',
  '要想活得痛快，身上不能背债。',
  'Happy is the man who learns from the misfortunes of others.',
  '吸取他人教训，自己才会走运。',
  'Harm set, harm get.',
  '害人害己。',
  'Hasty love, soon cold.',
  '一见钟情难维久。',
  'Health is better than wealth.',
  '健康胜过财富。',
  'Health is happiness.',
  '健康就是幸福。',
  'Hear all parties.',
  '兼听则明。',
  'Heaven never helps the man who will not act.',
  '自己不动，叫天何用。',
  'He is a fool that forgets himself.',
  '愚者忘乎所以。',
  'He is a good friend that speaks well of us behind our backs.',
  '背后说好话，才是真朋友。',
  'He is a wise man who speaks little.',
  '聪明不是挂在嘴上。',
  'He is lifeless that is faultless.',
  '只有死人才不犯错误。',
  'He is not fit to command others that cannot command himself.',
  '正人先正己。',
  'He is not laughed at that laughs at himself first.',
  '自嘲者不会让人见笑。',
  'He is wise that is honest.',
  '诚实者最明智。',
  'He knows most who speaks least.',
  '大智若愚。',
  'He laughs best who laughs last.',
  '谁笑到最后，谁笑得最好。',
  'He sets the fox to keep the geese.',
  '引狼入室。',
  'He that climbs high falls heavily.',
  '爬得越高，摔得越重。',
  'He that will not work shall not eat.',
  '不劳动者不得食。',
  'He who does not advance loses ground.',
  '逆水行舟，不进则退。',
  'He who makes constant complaint gets little compassion.',
  '经常诉苦，没人同情。',
  'He who makes no mistakes makes nothing.',
  '想不犯错误，就一事无成。',
  'He who risks nothing gains nothing.',
  '收获与风险并存。',
  'History repeats itself.',
  '历史往往重演。',
  'Honesty is the best policy.',
  '做人诚信为本。',
  'Hope for the best, but prepare for the worst.',
  '抱最好的愿望，做最坏的打算。',
  'I cannot be your friend and your flatterer too.',
  '朋友不能阿谀奉承。',
  'If a man deceives me once, shame on him, if he deceives me twice, shame on me.',
  '上当一回头，再多就可耻。',
  'If you make yourself an ass, don\'t complain if people ride you.',
  '人善被人欺，马善被人骑。',
  'If your ears glow, someone is talking of you.',
  '耳朵发烧，有人念叨。',
  'If you run after two hares, you will catch neither.',
  '脚踏两条船，必定落空。',
  'If you sell the cow, you sell her milk too.',
  '杀鸡取卵。',
  'If you venture nothing, you will have nothing.',
  '不入虎穴，焉得虎子。',
  'If you want knowledge, you must toil for it.',
  '要想求知，就得吃苦。',
  'Industry is the parent of success.',
  '勤奋是成功之母。',
  'It is better to die when life is a disgrace.',
  '宁为玉碎，不为瓦全。',
  'It is easier to get money than to keep it.',
  '挣钱容易攒钱难。',
  'It is easy to be wise after the event.',
  '事后诸葛亮好当。',
  'It is easy to open a shop but hard to keep it always open.',
  '创业容易守业难。',
  'It is hard to please all.',
  '众口难调。',
  'It is never too old to learn.',
  '活到老，学到老。',
  'It is no use crying over spilt milk.',
  '覆水难收。',
  'It is the first step that costs troublesome.',
  '万事开头难。',
  'It is the unforeseen that always happens.',
  '天有不测风云，人有旦夕祸福。',
  'It is too late to grieve when the chance is past.',
  '坐失良机，后悔已迟。',
  'It never rains but it pours.',
  '不鸣则已，一鸣惊人。',
  'It takes three generations to make a gentleman.',
  '十年树木，百年树人。',
  'Jack of all trades and master of none.',
  '门门精通，样样稀松。',
  'Judge not from appearances.',
  '人不可貌相，海不可斗量。',
  'Justice has long arms.',
  '天网恢恢，疏而不漏。',
  'Keep good men company and you shall be of the number.',
  '近朱者赤，近墨者黑。',
  'Kill two birds with one stone.',
  '一箭双雕。',
  'Kings go mad, and the people suffer for it.',
  '君王发狂，百姓遭殃。',
  'Kings have long arms.',
  '普天之下，莫非王土。',
  'Knowledge is power.',
  '知识就是力量。',
  'Knowledge makes humble, ignorance makes proud.',
  '博学使人谦逊，无知使人骄傲。',
  'Learn and live.',
  '活着，为了学习。',
  'Learning makes a good man better and ill man worse.',
  '好人越学越好，坏人越学越坏。',
  'Learn not and know not.',
  '不学无术。',
  'Learn to walk before you run.',
  '先学走，再学跑。',
  'Let bygones be bygones.',
  '过去的就让它过去吧。',
  'Let sleeping dogs lie.',
  '别惹麻烦。',
  'Let the cat out of the bag.',
  '泄漏天机。',
  'Lies can never changes fact.',
  '谎言终究是谎言。',
  'Lies have short legs.',
  '谎言站不长。',
  'Life is but a span.',
  '人生苦短。',
  'Life is half spent before we know what it is.',
  '人过半生，方知天命。',
  'Life is not all roses.',
  '人生并不是康庄大道。',
  'Life without a friend is death.',
  '没有朋友，虽生犹死。',
  'Like a rat in a hole.',
  '瓮中之鳖。',
  'Like author, like book.',
  '文如其人。',
  'Like father, like son.',
  '有其父必有其子。',
  'Like for like.',
  '一报还一报。',
  'Like knows like.',
  '惺惺相惜。',
  'Like mother, like daughter.',
  '有其母必有其女。',
  'Like teacher, like pupil.',
  '什么样的老师教什么样的学生。',
  'Like tree, like fruit.',
  '羊毛出在羊身上。',
  'Little things amuse little minds.',
  '小人无大志。',
  'Look before you leap.',
  '摸清情况再行动。',
  'Lookers-on see more than players.',
  '当局者迷，旁观者清。',
  'Losers are always in the wrong.',
  '胜者为王，败者为寇。',
  'Lost time is never found again.',
  '岁月既往，一去不回。',
  'Love at first sight.',
  '一见钟情。',
  'Love cannot be compelled.',
  '爱情不能强求。',
  'Love is blind.',
  '爱情是盲目的。',
  'Love is full of trouble.',
  '爱情充满烦恼。',
  'Love is never without jealousy.',
  '没有妒忌就没有爱情。',
  'Love me, love my dog.',
  '爱屋及乌。',
  'Make hay while the sun shines.',
  '良机勿失。',
  'Make your enemy your friend.',
  '化敌为友。',
  'Man is the soul of the universe.',
  '人是万物之灵。',
  'Man proposes, God disposes.',
  '谋事在人，成事在天。',
  'Many hands make light work.',
  '众人拾柴火焰高。',
  'Many heads are better than one.',
  '三个臭皮匠，赛过诸葛亮。',
  'Many things grow in the garden that were never sown there.',
  '有心栽花花不发，无心插柳柳成荫。',
  'Measure for measure.',
  '针锋相对。',
  'Misfortunes never come alone.',
  '祸不单行。',
  'Misfortune tests the sincerity of friends.',
  '患难见真情。',
  'Money isn\'t everything.',
  '钱不是万能的。',
  'Murder will out.',
  '纸包不住火。',
  'My son is my son till he has got him a wife, but my daughter is my daughter all the days of her life.',
  '儿子婚前是儿子，女儿终生是女儿。',
  'Nature is the true law.',
  '天行有常，不为尧存，不为桀亡。',
  'Necessity is the mother of invention.',
  '需要是发明的动力。',
  'Never fish in trouble water.',
  '不要混水摸鱼。',
  'Never judge from appearances.',
  '不可以貌取人。',
  'Never say die.',
  '永不言败。',
  'Never too old to learn, never too late to turn.',
  '亡羊补牢，为时未晚。',
  'New wine in old bottles.',
  '旧瓶装新酒。',
  'No cross, no crown.',
  '不经历风雨，怎么见彩虹。',
  'No garden without its weeds.',
  '没有不长草的园子。',
  'No living man all things can.',
  '世上没有万事通。',
  'No man can do two things at once.',
  '一心不可二用。',
  'No man is born wise or learned.',
  '没有生而知之者。',
  'No man is content.',
  '人心不足蛇吞象。',
  'No man is wise at all times.',
  '聪明一世，糊涂一时。',
  'None are so blind as those who won\'t see.',
  '视而不见。',
  'None are so deaf as those who won\'t hear.',
  '充耳不闻。',
  'No news is good news.',
  '没有消息就是好消息。',
  'No one can call back yesterday.',
  '昨日不会重现。',
  'No pains, no gains.',
  '没有付出就没有收获。',
  'No pleasure without pain.',
  '没有苦就没有乐。',
  'No rose without a thorn.',
  '没有不带刺的玫瑰。',
  'No sweet without sweat.',
  '先苦后甜。',
  'No smoke without fire.',
  '无风不起浪。',
  'Nothing brave, nothing have.',
  '不入虎穴，焉得虎子。',
  'Nothing dries sooner than a tear.',
  '眼泪干得最快。',
  'Nothing in the world is difficult for one who sets his mind to it.',
  '世上无难事，只怕有心人。',
  'Nothing is difficult to the man who will try.',
  '世上无难事，只要肯登攀。',
  'Nothing seek, nothing find.',
  '没有追求就没有收获。',
  'Nothing is so necessary for travelers as languages.',
  '外出旅行，语言最要紧。',
  'Nothing is to be got without pains but poverty.',
  '世上唯有贫穷可以不劳而获。',
  'Not to advance is to go back.',
  '不进则退。',
  'Not to know what happened before one was born is always to be a child.',
  '不懂世故，幼稚可笑。',
  'No way is impossible to courage.',
  '勇者无惧。',
  'Obedience is the first duty of a soldier.',
  '军人以服从命令为天职。',
  'Observation is the best teacher.',
  '观察是最好的老师。',
  'Offense is the best defense.',
  '进攻是最好的防御。',
  'Old friends and old wines are best.',
  '陈酒味醇，老友情深。',
  'Old sin makes new shame.',
  '一失足成千古恨。',
  'Once a man and twice a child.',
  '一次老，两次小。',
  'Once a thief, always a thief.',
  '偷盗一次，做贼一世。',
  'Once bitten, twice shy.',
  '一朝被蛇咬，十年怕井绳。',
  'One boy is a boy, two boys half a boy, three boys no boy.',
  '一个和尚挑水喝，两个和尚抬水喝，三个和尚没水喝。',
  'One cannot put back the clock.',
  '时钟不能倒转。',
  'One eyewitness is better than ten hearsays.',
  '百闻不如一见。',
  'One false move may lose the game.',
  '一着不慎，满盘皆输。',
  'One good turn deserves another.',
  '行善积德。',
  'One hour today is worth two tomorrow.',
  '争分夺秒效率高。',
  'One man\'s fault is other man\'s lesson.',
  '前车之鉴。',
  'One never loses anything by politeness.',
  '讲礼貌不吃亏。',
  'One swallow does not make a summer.',
  '一燕不成夏。',
  'One\'s words reflect one\'s thinking.',
  '言为心声。',
  'Out of debt, out of danger.',
  '无债一身轻。',
  'Out of office, out of danger.',
  '无官一身轻。',
  'Out of sight, out of mind.',
  '眼不见，心为静。',
  'Patience is the best remedy.',
  '忍耐是良药。',
  'Penny wise, pound foolish.',
  '贪小便宜吃大亏。',
  'Plain dealing is praised more than practiced.',
  '正大光明者，说到的多，做到的少。',
  'Please the eye and plague the heart.',
  '贪图一时快活，必然留下隐祸。',
  'Pleasure comes through toil.',
  '苦尽甘来。',
  'Pour water into a sieve.',
  '竹篮子打水一场空。',
  'Practice makes perfect.',
  '熟能生巧。',
  'Praise is not pudding.',
  '恭维话不能当饭吃。',
  'Praise makes good men better, and bad men worse.',
  '好人越夸越好，坏人越夸越糟。',
  'Prefer loss to unjust gain.',
  '宁可吃亏，不贪便宜。',
  'Prevention is better than cure.',
  '预防胜于治疗。',
  'Pride goes before, and shame comes after.',
  '骄傲使人落后。',
  'Promise is debt.',
  '一诺千金。',
  'Proverbs are the daughters of daily experience.',
  '谚语是日常经验的结晶。',
  'Pull the chestnut out of fire.',
  '火中取栗。',
  'Put the cart before the horse.',
  '本末倒置。',
  'Put your shoulder to the wheel.',
  '鼎力相助。',
  'Reading enriches the mind.',
  '开卷有益。',
  'Reading is to the mind while exercise to the body.',
  '读书健脑，运动强身。',
  'Respect yourself, or no one else will respect you.',
  '要人尊敬，必须自重。',
  'Rome is not built in a day.',
  '冰冻三尺，非一日之寒。',
  'Saying is one thing and doing another.',
  '言行不一。',
  'Seeing is believing.',
  '眼见为实。',
  'Seek the truth from facts.',
  '实事求是。',
  'Send a wise man on an errand, and say nothing to him.',
  '智者当差，不用交代。',
  'Set a thief to catch a thief.',
  '以贼捉贼。',
  'Short accounts make long friends.',
  '好朋友勤算账。',
  'Something is better than nothing.',
  '聊胜于无。',
  'Soon learn, soon forgotten.',
  '学得快，忘得快。',
  'Soon ripe, soon rotten.',
  '熟得快，烂得快。',
  'Speech is silver, silence is gold.',
  '能言是银，沉默是金。',
  'Still water run deep.',
  '静水常深。',
  'Strike the iron while it is hot.',
  '趁热打铁。',
  'Success belongs to the persevering.',
  '坚持就是胜利。',
  'Take things as they come.',
  '既来之，则安之。',
  'Talking mends no holes.',
  '空谈无补。',
  'Talk of the devil and he will appear.',
  '说曹操，曹操就到。',
  'Tall trees catch much wind.',
  '树大招风。',
  'Teach others by your example.',
  '躬亲示范。',
  'The best hearts are always the bravest.',
  '无私者无畏。',
  'The best man stumbles.',
  '伟人也有犯错时。',
  'The cat shuts its eyes when stealing.',
  '掩耳盗铃。',
  'The danger past and God forgotten.',
  '过河拆桥。',
  'The darkest hour is nearest the dawn.',
  '黎明前的黑暗。',
  'The darkest place is under the candlestick.',
  '烛台底下最暗。',
  'The devil knows many things because he is old.',
  '老马识途。',
  'The devil sometimes speaks the truth.',
  '魔鬼有时也会说真话。',
  'The die is cast.',
  '木已成舟。',
  'The early bird catches the worm.',
  '早起的鸟儿有虫吃。',
  'The end justifies the means.',
  '只要目的正当，可以不择手段。',
  'The end makes all equal.',
  '死亡面前，人人平等。',
  'The eye is bigger than the belly.',
  '贪多嚼不烂。',
  'The farthest way about is the nearest way home.',
  '抄近路反而绕远路。',
  'The finest diamond must be cut.',
  '玉不琢，不成器。',
  'The fire is the test of gold, adversity of strong man.',
  '烈火验真金，艰难磨意志。',
  'The first step is the only difficulty.',
  '迈出第一步是最艰难的。',
  'The fox knew too much, that\'s how he lost his tail.',
  '机关算尽太聪明，反误了卿卿性命。',
  'The fox preys farthest from home.',
  '兔子不吃窝边草。',
  'The frog in the well knows nothing of the great ocean.',
  '坐井观天。',
  'The grass is greener on the other side.',
  '这山望着那山高。',
  'The greatest talkers are always least doers.',
  '语言的巨人总是行动的矮子。',
  'The higher up, the greater the fall.',
  '爬得高，摔得惨。',
  'The leopard cannot change its spots.',
  '本性难移。',
  'The more noble, the more humble.',
  '人越高尚，越谦虚。',
  'The more wit, the less courage.',
  '初生牛犊不怕虎。',
  'The outsider sees the most of the game.',
  '旁观者清。',
  'The pen is mightier than the sword.',
  '笔能杀人。',
  'The pot calls the kettle black.',
  '五十步笑百步。',
  'There are spots in the sun.',
  '太阳也有黑点。',
  'There are two sides to every question.',
  '问题皆有两面。',
  'There is a skeleton in the cupboard.',
  '家家有本难念的经。',
  'There is kindness to be found everywhere.',
  '人间处处有温情。',
  'There is no general rule without some exception.',
  '任何法规均有例外。',
  'There is no medicine against death.',
  '没有长生不老药。',
  'There is no place like home.',
  '金窝银窝不如咱的狗窝。',
  'There is no royal road to learning.',
  '书山有路勤为径，学海无涯苦作舟。',
  'The style is the man.',
  '字如其人。',
  'The tongue is not steel, yet it cuts.',
  '人言可畏。',
  'The water that bears the boat is the same that swallows it up.',
  '水能载舟，亦能覆舟。',
  'The wise man knows he knows nothing, the fool thinks he knows all.',
  '清者自清，浊者自浊。',
  'The wolf has a winning game when the shepherds quarrel.',
  '螳螂捕蝉，黄雀在后。',
  'The world is a ladder for some to go up and others to go down.',
  '世界如阶梯，有人上有人下。',
  'The world is but a little place, after all.',
  '海内存知己，天涯若比邻。',
  'Think twice before you do.',
  '三思而后行。',
  'Things at the worst will mend.',
  '否极泰来。',
  'Time and tide wait for no man.',
  '时不我待。',
  'Time cures all things.',
  '时间是医治一切创伤的良药。',
  'Time flies.',
  '光阴似箭。',
  'Time is money.',
  '时间就是金钱。',
  'Time lost cannot be won again.',
  '时光流逝，不可复得。',
  'Time past cannot be called back again.',
  '时间不能倒流。',
  'Time tries all.',
  '路遥知马力，日久见人心。',
  'Tit for tat is fair play.',
  '人不犯我，我不犯人；人若犯我，我必犯人。',
  'To err is human.',
  '人非圣贤，孰能无过。',
  'To know everything is to know nothing.',
  '什么都知道，一如什么都不知道。',
  'To know oneself is true progress.',
  '人贵有自知之明。',
  'Tomorrow never comes.',
  '我生待明日，万事成蹉跎。',
  'Too much familiarity breeds contempt.',
  '过分熟悉会使人互不服气。',
  'Too much knowledge makes the head bald.',
  '学问太多催人老。',
  'Too much liberty spills all.',
  '自由放任，一事无成。',
  'Too much praise is a burden.',
  '过多夸奖，反成负担。',
  'To save time is to lengthen life.',
  '节约时间就是延长生命。',
  'Touch pitch, and you will be defiled.',
  '常在河边走，哪有不湿鞋。',
  'Troubles never come singly.',
  '福无双至，祸不单行。',
  'Truth never grows old.',
  '真理永存。',
  'Turn over a new leaf.',
  '洗心革面，改过自新。',
  'Two dogs strive for a bone, and a third runs away with it.',
  '鹬蚌相争，渔翁得利。',
  'Two heads are better than one.',
  '一个好汉三个帮。',
  'Two of a trade seldom agree.',
  '同行是冤家。',
  'Two wrongs do not make a right.',
  '别人错了，不等于你对了。',
  'Unity is strength.',
  '团结就是力量。',
  'Unpleasant advice is a good medicine.',
  '忠言逆耳利于行。',
  'Until all is over one\'s ambition never dies.',
  '不到黄河心不死。',
  'Venture a small fish to catch a great one.',
  '吃小亏占大便宜。',
  'Virtue is fairer far than beauty.',
  '美德远远胜过美貌。',
  'Walls have ears.',
  '小心隔墙有耳。',
  'Wash your dirty linen at home.',
  '家丑不可外扬。',
  'Water dropping day by day wears the hardest rock away.',
  '滴水穿石。',
  'Wealth is nothing without health.',
  '失去健康，钱再多也没用。',
  'We know not what is good until we have lost it.',
  '好东西，失去了才明白。',
  'Well begun is half done.',
  '好的开始，是成功的一半。',
  'We never know the worth of water till the well is dry.',
  '井干方知水可贵。',
  'We shall never have friends if we expect to find them without fault.',
  '欲求完美无缺的朋友必然成为孤家寡人。',
  'We should never remember the benefits we have offered nor forget the favor received.',
  '自己的好事别去提，别人的恩惠要铭记。',
  'Wet behind the ears.',
  '乳臭未干。',
  'Whatever you do, do with all your might.',
  '不管做什么，都要一心一意。',
  'What is learned in the cradle is carried to the grave.',
  '儿时所学，终生难忘。',
  'What\'s done cannot be undone.',
  '生米煮成熟饭了。',
  'What\'s lost is lost.',
  '失者不可复得。',
  'What we do willingly is easy.',
  '愿者不难。',
  'When in Rome, do as the Romans do.',
  '入国问禁，入乡随俗。',
  'When everybody\'s somebody then nobody\'s anybody.',
  '人人都伟大，世间没豪杰。',
  'When sorrow is asleep, wake it not.',
  '伤心旧事别重提。',
  'When sorrows come, they come not single spies, but in battalions.',
  '新仇旧恨，齐上心头。',
  'When the fox preaches, take care of your geese.',
  '黄鼠狼给鸡拜年，没安好心。',
  'When wine is in truth, wit is out.',
  '酒后吐真言。',
  'Where there is a will, there is a way.',
  '有志者事竟成。',
  'Where there is life, there is hope.',
  '留得青山在，不怕没柴烧。',
  'Where there is smoke, there is fire.',
  '事出有因。',
  'While the priest climbs a post, the devil climbs ten.',
  '道高一尺，魔高一丈。',
  'Who chatters to you, will chatter of you.',
  '搬弄口舌者必是小人。',
  'Whom the gods love die young.',
  '好人不长命。',
  'Wise man have their mouths in their hearts, fools have their hearts in their mouths.',
  '智者嘴在心里，愚者心在嘴里。',
  'Work makes the workman.',
  '勤工出巧匠。',
  'You cannot burn the candle at both ends.',
  '蜡烛不能两头点，精力不可过分耗。',
  'You cannot eat your cake and have it.',
  '鱼与熊掌，不可得兼。',
  'You can take a horse to the water but you cannot make him drink.',
  '强扭的瓜不甜。',
  'You may know by a handful the whole sack.',
  '由一斑可知全貌。',
  'You never know what you can till you try.',
  '是驴子是马，拉出来遛遛。'
];
